### ISSUE TITLE
Libs Error

### ISSUE THREAD

**Issue by WashingMachine** [shirsig/cooldowns#2]
Error: Interface\AddOns\cooldowns\libs\T.lua:1: attempt to call global 'defined' (a nil value)

No target cooldowns are shown (I think becuase of this error)

**Comment by shirsig** [comment]
I think either you didn't do a clean install or some other addon is interfering because it's defined right here https://github.com/shirsig/cooldowns/blob/master/libs/module.lua#L65

**Comment by WashingMachine** [comment]
You are right, after a clean install, it all works fine now.
Thank you and sorry to bother you.
