### ISSUE TITLE
Error When Trying to See the Ignore List

### ISSUE THREAD

**Issue by kyresong** [shirsig/cooldowns#3]
When I type `/cooldowns ignore`, I get an error (attached a screenshot). Not a big issue, but wanted to let you know.

Thank you for creating such an awesome addon. It’s so much better to have all my cooldowns in one place, so I don't have to look at the action bar.

![error](https://cloud.githubusercontent.com/assets/18236471/21075794/8831d35c-bf23-11e6-8667-63e8e32b8fe5.jpg)

**Comment by shirsig** [comment]
thanks, fixed
