### ISSUE TITLE
Not an issue, only a request/question

### ISSUE THREAD

**Issue by Oliveryo** [shirsig/cooldowns#4]
Hello, very nice addon.
Is it possible to always show cooldowns?
Not only show when they are on cd.
Regards Oliver

**Comment by Oliveryo** [comment]
And how do I disable targets target cds?

**Comment by shirsig** [comment]
You disable them with /cooldowns targettarget off
Though they already should be disabled by default.
As for showing abilities off cooldown, not sure if that makes sense. There are too many and most of them aren't that interesting. You should probably just use powerauras for that.

**Comment by Oliveryo** [comment]
Okay thanks, I know there is too many I was just thinking if there is a way to always show some of my own spells. Would look very clean.
