### ISSUE TITLE
Error:  attempt to index global `cooldowns_settings' (a nil value)

### ISSUE THREAD

**Issue by twistt89** [shirsig/cooldowns#5]
Error:  attempt to index global `cooldowns_settings' (a nil value)
File: Interface\AddOns\cooldowns\player.lua
Line: 11
Count: 1

Would be awesome if you could help :)

**Comment by shirsig** [comment]
You probably just need to delete the savedvariables

**Comment by twistt89** [comment]
Hey , thanks for the reply I tried to delete the SharedVariables folder , Savedvariables.lua and savedvariables.lua.bak.  With all these deleted still no luck, Tried to reinstall multiple times as well.

**Comment by shirsig** [comment]
maybe it was the wrong one? there are two savedvariables folders. one per character and one per account. you need to get the one for the account. also, you need to delete it while you're not logged in or it will reset.

**Comment by twistt89** [comment]
Just tried again following your directions but still getting the same error.

**Comment by twistt89** [comment]
Also tried disabling every other addon incase it was a conflict of addons.

**Comment by shirsig** [comment]
hm, it seems it's not enough to log out for the account wide file, you need to completely close the client

**Comment by twistt89** [comment]
Very nice! now working! error message gone, thank you very much.
